steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/spinnaker-252016/gcpnlp:$TAG_NAME','.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/spinnaker-252016/gcpnlp:$TAG_NAME']
