apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nlp
spec:
 rules:
  - host: gkestage.kamalsblog.com
    http:
      paths: 
      - backend:
          serviceName: nlpappserv
          servicePort: 3000